/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Message = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'conversation' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'clearAllMessages' : IDL.Func([], [], []),
  'deleteMessage' : IDL.Func([IDL.Text], [], []),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'saveMessages' : IDL.Func([IDL.Vec(Message)], [], []),
  'seedDemoMessages' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Message = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'conversation' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'clearAllMessages' : IDL.Func([], [], []),
    'deleteMessage' : IDL.Func([IDL.Text], [], []),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'saveMessages' : IDL.Func([IDL.Vec(Message)], [], []),
    'seedDemoMessages' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };